language: ruby
rvm:
  - ruby-2.0.0
before_script:
  - psql -c 'create database "engine-light_test";' -U postgres
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/98138ce2-1d31-4eac-91b8-55e763474cc9/status