language: ruby
rvm:
  - ruby-2.0.0
addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update
  - sudo find / -name "geos"
  - sudo find / -name "proj"
  - ls /usr/share/proj
  - ls /usr/bin/proj
  - sudo find / -name "gdal"
  - ls /usr/share/gdal
  - sudo apt-get install -qq libgeos-dev libproj-dev
  - sudo apt-get -qq install libgeos++-dev
  - sudo find / -name "geos"
  - ls /usr/include/geos
  - sudo find / -name "proj"
  - ls /usr/share/proj
  - ls /usr/bin/proj
  - sudo find / -name "gdal"
  - ls /usr/share/gdal

before_script:
  
  - gem uninstall rgeo
  - gem install rgeo -- --with-geos-dir=/usr/include/geos --with-proj-dir=/usr/share/proj
  - irb
  - require 'rgeo'
  - RGeo::Geos.supported?
  - quit
  - psql -c 'create database "homebase_test";' -U postgres
  - psql -U postgres -c "create extension postgis"
  - bundle exec rake db:migrate RAILS_ENV=test
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/98138ce2-1d31-4eac-91b8-55e763474cc9/status